export const avatarDescription = [
  'Sombrerro man',
  'Punk boy 1',
  'Nice pirate',
  'Punk boy 2',
  'Grandma',
  'Blue-hair girl',
  'Pink-hair woman',
  'Santa Clause',
  'Cinderella',
  'Thai-girl',
  'Programmer',
  'Masked cowboy',
  'Beard man',
  'Beard woman',
  'Pirate girl',
  'Mustache man',
];
